# This file was generated by GoReleaser. DO NOT EDIT.
cask "asymptote" do
  name "asymptote"
  desc "CLI for Asymptote security platform"
  homepage "https://asymptotelabs.ai"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asymptote"

  on_macos do
    on_intel do
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v#{version}/asymptote_#{version}_darwin_amd64.tar.gz"
      sha256 "250607d21816052681c360565e16045573f3a1642af81d6ed7e7087bfdb3dcf2"
    end
    on_arm do
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v#{version}/asymptote_#{version}_darwin_arm64.tar.gz"
      sha256 "6634e3265f2defd74de9619b3962ae43051bd66dea51c41ac2f5cb5a5839d505"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v#{version}/asymptote_#{version}_linux_amd64.tar.gz"
      sha256 "7c9af2ff3265368fa89e7376cdae89e286b0e2f3c33cc7f7e2a7148b64c26575"
    end
    on_arm do
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v#{version}/asymptote_#{version}_linux_arm64.tar.gz"
      sha256 "8cb39b7c296e46871005f462c5c7ce6faeca5d4ea5c62e5b135d1b5b26e5e3ce"
    end
  end

  # No zap stanza required
end
