# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asymptote < Formula
  desc "CLI for Asymptote security platform"
  homepage "https://asymptotelabs.ai"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v1.1.1/asymptote_1.1.1_darwin_amd64.tar.gz"
      sha256 "a924c0e633681a7b5d31eb6834772158746721adbfe19f607f681c984375f9ca"

      def install
        bin.install "asymptote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v1.1.1/asymptote_1.1.1_darwin_arm64.tar.gz"
      sha256 "e1207f8fc3e311a64e63933305d561f33633fd61125af4f9ba9d169be87b1796"

      def install
        bin.install "asymptote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v1.1.1/asymptote_1.1.1_linux_amd64.tar.gz"
      sha256 "cd824e4b998edb07a360fdd7ea927f6bb5981355f23799df94b2619d6472a92b"
      def install
        bin.install "asymptote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v1.1.1/asymptote_1.1.1_linux_arm64.tar.gz"
      sha256 "b601fc5b1e781a5009ecd5d0b1345c26f7d142e3c03332112f62b3e46253284c"
      def install
        bin.install "asymptote"
      end
    end
  end

  test do
    system "#{bin}/asymptote", "version"
  end
end
