# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asymptote < Formula
  desc "CLI for Asymptote security platform"
  homepage "https://asymptotelabs.ai"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asymptote-labs/asymptote-code/releases/download/v0.1.0/asymptote_0.1.0_darwin_amd64.tar.gz"
      sha256 "2a6f39b88377641ce1405ce9e9591054d5bf44cd09429c02f53c317217b37662"

      def install
        bin.install "asymptote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asymptote-labs/asymptote-code/releases/download/v0.1.0/asymptote_0.1.0_darwin_arm64.tar.gz"
      sha256 "a90edf285b19a35131fd2ce9421cd84b16b112c0f99a9349a9704b03dc230893"

      def install
        bin.install "asymptote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/asymptote-code/releases/download/v0.1.0/asymptote_0.1.0_linux_amd64.tar.gz"
      sha256 "bb02b2469118401a66f4ee07ba168afdc1e8ad31dd1dbf6b06b1523cdef182ef"
      def install
        bin.install "asymptote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/asymptote-code/releases/download/v0.1.0/asymptote_0.1.0_linux_arm64.tar.gz"
      sha256 "f43abf6bc2e20c642b5e54418429d7f2096862667b4639fb04fe3bcab481de0c"
      def install
        bin.install "asymptote"
      end
    end
  end

  test do
    system "#{bin}/asymptote", "version"
  end
end
