# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asymptote < Formula
  desc "CLI for Asymptote security platform"
  homepage "https://asymptotelabs.ai"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v1.1.0/asymptote_1.1.0_darwin_amd64.tar.gz"
      sha256 "8b25df593eb1e35f068b0e0e488b4eb7d59de479f0b93e9522d09581fcbda1f2"

      def install
        bin.install "asymptote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v1.1.0/asymptote_1.1.0_darwin_arm64.tar.gz"
      sha256 "57662740d9e76ea93645b200cc7e6fe390417600fea238b1a295b8196eac8300"

      def install
        bin.install "asymptote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v1.1.0/asymptote_1.1.0_linux_amd64.tar.gz"
      sha256 "57421fd56938d20b579b68bbd3665be458318e5990717dad05be9367ad49c36a"
      def install
        bin.install "asymptote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v1.1.0/asymptote_1.1.0_linux_arm64.tar.gz"
      sha256 "618578241ca2bfb62b3ecb8e845227ae6794277cfe5fbf1e32f9642384607a96"
      def install
        bin.install "asymptote"
      end
    end
  end

  test do
    system "#{bin}/asymptote", "version"
  end
end
