# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsymptoteCli < Formula
  desc "CLI for Asymptote security platform"
  homepage "https://asymptotelabs.ai"
  version "2.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v2.7.0/asym_2.7.0_darwin_amd64.tar.gz"
      sha256 "6fd6bd9cf5310c33d527ab81243298ce084db71196c07b43123b6054bedd4cc2"

      define_method(:install) do
        bin.install "asym"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v2.7.0/asym_2.7.0_darwin_arm64.tar.gz"
      sha256 "64b750806571fdc44b2779fd252f7eaaddd0cfaf49cd92a8c28e2503100dd1c5"

      define_method(:install) do
        bin.install "asym"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v2.7.0/asym_2.7.0_linux_amd64.tar.gz"
      sha256 "ff55ce13c91fb8672a7a6bd53a4d242442a5cd3dd9d077e30f448efccf1db697"
      define_method(:install) do
        bin.install "asym"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/asymptote-cli/releases/download/v2.7.0/asym_2.7.0_linux_arm64.tar.gz"
      sha256 "02743b658cb250c197186f16cad4c3bf62cd55f1e9436425a1d833fca5608944"
      define_method(:install) do
        bin.install "asym"
      end
    end
  end

  def caveats
    <<~EOS
      To update your agent hooks to the latest version, run:
        asym upgrade
    EOS
  end

  test do
    system "#{bin}/asym", "version"
  end
end
