# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beacon < Formula
  desc "Open-source endpoint agent for local AI runtime telemetry"
  homepage "https://asymptotelabs.ai"
  version "0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.14/beacon_0.0.14_darwin_amd64.tar.gz"
      sha256 "c8a51395bc35aca674eda0bcd4edd0290dae8daf1710b5c81244f4ab1dde0541"

      def install
        bin.install "beacon"
        bin.install "beacon-otelcol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.14/beacon_0.0.14_darwin_arm64.tar.gz"
      sha256 "17f0c3cd562143065f2d8fb83f98ccdb3d3416210ff95816700bf7674c81143e"

      def install
        bin.install "beacon"
        bin.install "beacon-otelcol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.14/beacon_0.0.14_linux_amd64.tar.gz"
      sha256 "b0e32f83ec868d57ff3f3484dfd77cea769472d29ee88bb0abd0718e575f65f9"
      def install
        bin.install "beacon"
        bin.install "beacon-otelcol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.14/beacon_0.0.14_linux_arm64.tar.gz"
      sha256 "4347fe5445bc19c8f90364f80082df64b0fb88f4bbbb80c86bfca9bef31b9b18"
      def install
        bin.install "beacon"
        bin.install "beacon-otelcol"
      end
    end
  end

  def caveats
    <<~EOS
      To configure local endpoint telemetry, run:
        beacon endpoint install
    EOS
  end

  test do
    system "#{bin}/beacon", "version"
  end
end
