# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beacon < Formula
  desc "Open-source endpoint agent for local AI runtime telemetry"
  homepage "https://asymptotelabs.ai"
  version "0.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.21/beacon_0.0.21_darwin_amd64.tar.gz"
      sha256 "236c2b09ec5c8c3c0870c6699610a057acb2796c84731f546b5fe485bcb4fe76"

      def install
        bin.install "beacon"
        bin.install "beacon-otelcol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.21/beacon_0.0.21_darwin_arm64.tar.gz"
      sha256 "53079acead78ebc44b5b8eac51b9120e927d80e55ac4a4a0955e66c7b0c75bdf"

      def install
        bin.install "beacon"
        bin.install "beacon-otelcol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.21/beacon_0.0.21_linux_amd64.tar.gz"
      sha256 "2cada8c1f2a454e307aa6d907df9a93144a5bd1c7296415f10162f7973500bd1"
      def install
        bin.install "beacon"
        bin.install "beacon-otelcol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.21/beacon_0.0.21_linux_arm64.tar.gz"
      sha256 "7c963073f8da3444cd2755eaa495e39aece4d2c74c50c095558608c1c49c3e95"
      def install
        bin.install "beacon"
        bin.install "beacon-otelcol"
      end
    end
  end

  def caveats
    <<~EOS
      To configure local endpoint telemetry, run:
        beacon endpoint install
    EOS
  end

  test do
    system "#{bin}/beacon", "version"
  end
end
