# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beacon < Formula
  desc "Open-source endpoint agent for local AI runtime telemetry"
  homepage "https://asymptotelabs.ai"
  version "0.0.78"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.78/beacon_0.0.78_darwin_amd64.tar.gz"
      sha256 "ab2ce022d19a51145dded6fe29c55e8cebbb19de11ebb0b4a27c1d31bfbfe9cf"

      def install
        bin.install "beacon"
        bin.install "beacon-hooks"
        bin.install "beacon-otelcol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.78/beacon_0.0.78_darwin_arm64.tar.gz"
      sha256 "4c231561f966f52b13c5ff1fcb9c22705050876b582796c9f686571eee853949"

      def install
        bin.install "beacon"
        bin.install "beacon-hooks"
        bin.install "beacon-otelcol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.78/beacon_0.0.78_linux_amd64.tar.gz"
      sha256 "a60ecfbc5d2655637c626cb177e29be7956d5055e905170dbac8b094fe537119"
      def install
        bin.install "beacon"
        bin.install "beacon-hooks"
        bin.install "beacon-otelcol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asymptote-labs/agent-beacon/releases/download/v0.0.78/beacon_0.0.78_linux_arm64.tar.gz"
      sha256 "43a5d6de01010f9209860cf424b626576055c1332766003d6d358ffea8e1f3bb"
      def install
        bin.install "beacon"
        bin.install "beacon-hooks"
        bin.install "beacon-otelcol"
      end
    end
  end

  def caveats
    <<~EOS
      To configure local endpoint telemetry, run:
        beacon endpoint install
    EOS
  end

  test do
    system "#{bin}/beacon", "version"
  end
end
